// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"app/internal/center/cmd"
	"app/internal/center/config"
	"app/internal/center/server"
	"app/internal/center/service"
	"app/internal/center/service/admin"
	"app/internal/center/service/rpc"
	"github.com/google/wire"
)

import (
	_ "embed"
)

// Injectors from wire.go:

func NewAdminAction() (*cmd.AdminAction, func()) {
	user := &admin.User{}
	service := &admin.Service{
		User: user,
	}
	adminServer := server.NewAdminServer(service)
	adminAction := &cmd.AdminAction{
		Server: adminServer,
	}
	return adminAction, func() {
	}
}

func NewRpcAction() (*cmd.RPCAction, func()) {
	configConfig := config.NewConfig()
	registry := config.NewEtcdRegister(configConfig)
	user := &rpc.User{
		Conf: configConfig,
	}
	service := &rpc.Service{
		User: user,
	}
	grpcServer := server.NewGRPCServer(registry, service)
	rpcAction := &cmd.RPCAction{
		Server: grpcServer,
	}
	return rpcAction, func() {
	}
}

// wire.go:

var providerSet = wire.NewSet(config.ProviderSet, server.NewAdminServer, server.NewGRPCServer, service.ProviderSet)
