// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: ai/center/admin/v1/login.proto

package admin

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserLoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户名
	UserName string `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	// 密码
	Pwd           string `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginRequest) Reset() {
	*x = UserLoginRequest{}
	mi := &file_ai_center_admin_v1_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginRequest) ProtoMessage() {}

func (x *UserLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_center_admin_v1_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginRequest.ProtoReflect.Descriptor instead.
func (*UserLoginRequest) Descriptor() ([]byte, []int) {
	return file_ai_center_admin_v1_login_proto_rawDescGZIP(), []int{0}
}

func (x *UserLoginRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserLoginRequest) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

type UserLoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户id
	UserId        int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginResponse) Reset() {
	*x = UserLoginResponse{}
	mi := &file_ai_center_admin_v1_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginResponse) ProtoMessage() {}

func (x *UserLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_center_admin_v1_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginResponse.ProtoReflect.Descriptor instead.
func (*UserLoginResponse) Descriptor() ([]byte, []int) {
	return file_ai_center_admin_v1_login_proto_rawDescGZIP(), []int{1}
}

func (x *UserLoginResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_ai_center_admin_v1_login_proto protoreflect.FileDescriptor

const file_ai_center_admin_v1_login_proto_rawDesc = "" +
	"\n" +
	"\x1eai/center/admin/v1/login.proto\x12\x12ai.center.admin.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x17validate/validate.proto\"Z\n" +
	"\x10UserLoginRequest\x12'\n" +
	"\bUserName\x18\x01 \x01(\tB\v\xe2A\x01\x02\xfaB\x04r\x02\x10\x01R\bUserName\x12\x1d\n" +
	"\x03pwd\x18\x02 \x01(\tB\v\xe2A\x01\x02\xfaB\x04r\x02\x10\x01R\x03pwd\",\n" +
	"\x11UserLoginResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId2\x81\x01\n" +
	"\x04User\x12y\n" +
	"\x05Login\x12$.ai.center.admin.v1.UserLoginRequest\x1a%.ai.center.admin.v1.UserLoginResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/center/admin/user/loginB6Z4github.com/97wsn/ai-center/api/center/admin/v1;adminb\x06proto3"

var (
	file_ai_center_admin_v1_login_proto_rawDescOnce sync.Once
	file_ai_center_admin_v1_login_proto_rawDescData []byte
)

func file_ai_center_admin_v1_login_proto_rawDescGZIP() []byte {
	file_ai_center_admin_v1_login_proto_rawDescOnce.Do(func() {
		file_ai_center_admin_v1_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_center_admin_v1_login_proto_rawDesc), len(file_ai_center_admin_v1_login_proto_rawDesc)))
	})
	return file_ai_center_admin_v1_login_proto_rawDescData
}

var file_ai_center_admin_v1_login_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ai_center_admin_v1_login_proto_goTypes = []any{
	(*UserLoginRequest)(nil),  // 0: ai.center.admin.v1.UserLoginRequest
	(*UserLoginResponse)(nil), // 1: ai.center.admin.v1.UserLoginResponse
}
var file_ai_center_admin_v1_login_proto_depIdxs = []int32{
	0, // 0: ai.center.admin.v1.User.Login:input_type -> ai.center.admin.v1.UserLoginRequest
	1, // 1: ai.center.admin.v1.User.Login:output_type -> ai.center.admin.v1.UserLoginResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_center_admin_v1_login_proto_init() }
func file_ai_center_admin_v1_login_proto_init() {
	if File_ai_center_admin_v1_login_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_center_admin_v1_login_proto_rawDesc), len(file_ai_center_admin_v1_login_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_center_admin_v1_login_proto_goTypes,
		DependencyIndexes: file_ai_center_admin_v1_login_proto_depIdxs,
		MessageInfos:      file_ai_center_admin_v1_login_proto_msgTypes,
	}.Build()
	File_ai_center_admin_v1_login_proto = out.File
	file_ai_center_admin_v1_login_proto_goTypes = nil
	file_ai_center_admin_v1_login_proto_depIdxs = nil
}
